import type { NextPage } from "next";
import Head from "next/head";
import { meta } from "@components/templates";

import { HomePage } from "@components/templates";
import { HomePageProps } from "@components/templates";
import { heroProps } from "@components/templates/HomePage/heroProps";
import { aboutProps } from "@components/templates/HomePage/aboutProps";
import { projectProps } from "@components/templates/HomePage/projectProps";

const homePage: HomePageProps = {
  heroProps,
  aboutProps,
  projectProps,
};

const Home: NextPage = () => {
  const title = `My Portfolio | ${meta.name}`;
  return (
    <>
      <Head>
        <title>{title}</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage {...homePage} />
    </>
  );
};

export default Home;
