import { AboutPageProps } from "./AboutPage";
import { meta } from "@components/templates";

export const aboutProps: AboutPageProps = {
  heroProps: {
    title: {
      name: meta.name,

      titles: [
        "Computer Scientist",
        "Tech Enthusiast",
        "Full-stack Engineer",
        "Communicator",
      ],
    },
  },

  journeyProps: {
    jobs: [
      {
        header: "Artologie",
        title: "Shopify Developer",
        date: "Dec 2021 – present",
        description: [
          "Built customized lightweight and modern Shopify themes utilizing newer web technologies, and JavaScript and CSS frameworks",
          "Provided efficient support and communication to the store owners in explaining technical information during website development.",
          "Maximized client satisfaction by catering an open approach during eCommerce development to meet dynamic client requirements.",
          "Migrated 2 existing Shopify storefronts onto newly designed custom-developed client-tailored themes within 1 month each.",
        ],
        langs: [
          "shopify",
          "alpine",
          "tailwind",
          "sass",
          "pwa",
          "googleAnalytics",
        ],
      },
      {
        header: "jasonm.co",
        title: "Shopify Developer",
        date: "Aug 2021 – Dec 2021",
        description: [
          'Utilized lazy-loading concepts to build a custom "Infinite scrolling" component that render products just-in-time while the user scrolls through the website, decreasing initial page load, and reducing user effort on paginated navigation to increase retention rate',
          "Created a private Shopify app to expose Shopify Storefront API and Admin API consumed with GraphQL endpoints.",
          "Developed a custom Python web-scraping script for automated product tagging and upload with images and descriptions from Google Search.",
          "Migrated an existing eCommerce Website from a different platform onto Shopify.",
        ],
        langs: [
          "shopify",
          "vue",
          "tailwind",
          "graphql",
          "python",
          "sass",
          "pwa",
          "googleAnalytics",
        ],
      },
      {
        header:
          "College of Computer and Information Science @ Malayan Colleges Laguna",
        title: "Assistant Researcher",
        date: "Jul 2021 – Aug 2021",
        description: [
          "Utilized bleeding edge JAMStack technologies and JavaScript frameworks such as Nuxt and ApexCharts.js to create beautiful and powerful chart components with dynamically fetched data.",
          "Optimized and abstracted existing codebase and data pipeline to ensure website accessibility for users with limited mobile data bandwidth, drastically reducing user data consumption and increasing Google Lighthouse performance metrics.",
          "Co-developed and deployed an automated Python web scrapping cloud function and data sanitizer on Microsoft Azure to fetch COVID-19 Case Data from the Google Drive data drop repository of the Department of Health.",
          "Integrated a CI/CD pipeline for continuous generation and deployment of the static website using data fetched from the automated web scrapping cloud function using Github Actions and Netlify.",
        ],
        langs: [
          "node",
          "nuxt",
          "vue",
          "tailwind",
          "sass",
          "pwa",
          "python",
          "apexCharts",
        ],
      },
    ],
  },

  educationProps: {
    schools: [
      {
        header: "Malayan Colleges Laguna",
        title: "Computer Scientist",
        date: "Aug 2018 – September 2022",
        description: [
          "Part of the school's representative team in the Lazada DevFest 2018 Rapid Web Development Competition, winning the Champion title and special awards for the Most Creative Team and Best Pitch.",
          "Designed and developed an event management and attendance website utilizing AJAX and jQuery to fetch and display real-time attendance data from a remote MySQL database server.",
          "Implemented object oriented design and principles in coding a text-based RPG adventure game with randomly generated game content using Python.",
          "Utilized data structure concepts to recycle and optimize usage of game object instances in Unity2D, reducing memory consumption, code complexity, and computational resources needed for rendering.",
          "Employed predictive modelling techniques such as Basic Classification, Naive Bayesian, and Ensemble Learning create a model that predicts heart diseases using limited patient data with an accuracy of 80%.",
        ],
        langs: [
          "react",
          "php",
          "laravel",
          "jquery",
          "graphql",
          "mysql",
          "tailwind",
          "bootstrap",
          "csharp",
          "unity",
          "python",
          "weka",
          "java",
          "kotlin",
          "android",
          "aws",
          "strapi",
          "heroku",
          "git",
          "github",
          "npm",
          "yarn",
          "pnpm",
          "webpack",
          "vite",
          "javascript",
          "html",
          "css",
          "bash",
          "windows",
          "linux",
        ],
      },
      {
        header: "Malayan Colleges Laguna",
        title: "ICT-Programming",
        date: "June 2016 – May 2018",
        description: [
          "Developed a professor's portal for tracking the attendance of students using LAMP stack.",
          "Developed a student's portal webpage targeted for incoming freshmen highlighting the SHS experience in MCL using Wix website builder",
        ],
        langs: [
          "php",
          "jquery",
          "mysql",
          "bootstrap",
          "csharp",
          "python",
          "java",
          "android",
          "git",
          "github",
          "npm",
          "webpack",
          "javascript",
          "html",
          "css",
        ],
      },
    ],
  },
};
